export const batch = [
  { pos: "F", name: "Taylor Hall", ov: 72 },
  { pos: "F", name: "Mikael Granlund", ov: 71 },
  { pos: "F", name: "Mikael Backlund", ov: 70 },
  { pos: "F", name: "Jean-Gabriel Pageau", ov: 67 },
  { pos: "F", name: "Mike Hoffman", ov: 66 },
  { pos: "F", name: "Lars Eller", ov: 66 },
  { pos: "F", name: "Nick Cousins", ov: 61 },
  { pos: "F", name: "Alex Chiasson", ov: 61 },
  { pos: "F", name: "Austin Watson", ov: 59 },
  { pos: "F", name: "Riley Nash", ov: 57 },
  { pos: "D", name: "Jeff Petry", ov: 69 },
  { pos: "D", name: "Anton Stralman", ov: 64 },
  { pos: "D", name: "Adam Larsson", ov: 64 },
  { pos: "D", name: "Erik Gudbranson", ov: 63 },
  { pos: "D", name: "Andrej Sekera", ov: 58 },
  { pos: "D", name: "Nick Blankenburg", ov: 46 },
  { pos: "G", name: "Casey Desmith", ov: 70 },
  { pos: "G", name: "Troy Grosenick", ov: 62 },
  { pos: "G", name: "Dylan Ferguson", ov: 57 }
];
